### ISSUE TITLE
Subsampling: add broken read flag

### ISSUE THREAD

**Issue by kristinelacek** [CDCgov/spyne#3]
Investigate and add either 'tossbrokenreads' or 'nullifybrokenquality' to reformat.sh

```bash
java.lang.Exception: 
Mismatch between length of bases and qualities for read 31926 (id=98952f97-d40d-48a3-bed4-1a1b9eb033e7 runid=499bc073a8fa80a288548c8a89f9f57a730eb3cd read=25334 ch=330 start_time=2023-06-14T18:06:13.180505+00:00 flow_cell_id=FAU05667 protocol_group_id=FLU_COVID_14062023 sample_id=no_sample barcode=barcode16 barcode_alias=barcode16 parent_read_id=98952f97-d40d-48a3-bed4-1a1b9eb033e7 basecall_model_version_id=2021-05-17_dna_r9.4.1_minion_384_d37a2ab9).
# qualities=1565, # bases=1535

)''(''''*('*0=<2234*'%$%%).1,(**++05,+*)*+(''(28)(((33607777544487.,,,,7:=<+***,-384))(./1:5455<64=>..-.8=A<;/--/3:8:>>2)))*2312<<:4492/--.3(''(21-)))(%%)***2,+0224=+*,,/57;6445C{B4445@?::66644*))*;?;<;<>BA>=<6667>>??5873/0001<<==66655433345/022350.-,..489=9876-.**,598;<900.+./34500..//+,*'(++,37<><<<66522234'/-**'&%%(((+84445.2.0)((2/6('/*)&&''(()*12*2/1766+*///0062523;787699:;=8677-,,.466(')+231(--.*,//33102478:7<AC75/44,,,-&%%%'1897-++*&&%%'-)(*762113;6569;;=<>87777=009765/0378333:9989<<<?B1640444468673:33--++*((&%%&&'(889:11111747669<:6*'(%%$%10+)*238+9643469898;:733,+,/.+++,68<<<=?<84333501('(1/0)53102)(')3*))((*&&&++0***334?>::@>=<<?:;9870+()3?=>;;89:83/+*&&(*,58:<9;,+++,++*)())&%%&()+8403'''(&&&%(&$$$$&&&;455489)(%'%%&149>GBE??<00,+))+7:;>88:5*''(()06762220.&&%%()2---2112*(+12:;;/.)((''),))))1000155+*.)))*000542214472'&&,0/)%$#$%()-.//'''(3445>9;::=@,*.)()11335:/20/016686512454:>:200000.''('*,.-177766795++2885998789;<<:>5212/.*((',-----8;72223;6=>;=>@BA=;<<;0...//;;--('&&$%&(+.6=>{{?;:3/*))2<:8:::6557<>?663345<;<==?=+)()0/089;?>66443...1111234:875358A@@<;66000/44579:>?64454---,('()12365568>77150+*+'(())++,0.-/46((((*)**,,22,(+122'*)4+69,4,,)-))-14599::9::;::::=>?;93203322111(((*9;<BGC=<9:789'''';:4355555.,/4/,1../0566;ABBA962231227700287:674455000,,/010..+.555;=<;:;@=::342+*+))*('(+-0)(&&''85556?=;99>67//...2/*)+-.3283/(''(./46:<@>:=743005(*+//33;:=?<;<<?><(,3,a*)+-700;:=?667//;(())+>//;f-@=?66787;99>.555;4770=74VA<3)-))-0.32BA=G+=9::;:5;=670;:=>//nUT=7-TTTC86*''(()06<:i255;842'&?+c4@()0'((>(()06)=?66+6:<@,o30;.-/46(()-14-5(''1>.c:,
GTGTACTTCACGTTCAGTTACGCATTGCTAAGGTTAACGTCAGCTGACAGTGGTTCGTATAGCACCTACGTGATCAGCAAAAGCAGGGGACAGTCCCATCGGCAAAGTCGGGGAACTTCCAGGAAGCCCGCGTCCCCTCAACCTGCCTTTAGCCAGAAAAGATTCCAAGCTCTGCTCTCTACTTTGGAAAGCCAGTGTTTGCATGTGGAGATTGTTTTGCTGAACTCGACGAGGGTAGCAAAGCAACAGGAAGTGTTCCCCAGGCTCCGCCCACGACTTGCGTGGCCCAAAGCTGGATGGTCGTCCGTCCTACATAGCAGGTGGGTAAGGTTCTTTTCTGGGCTGCAATCATTCCACCCAGAGCAAGGGATAAGCCTGTGATAGCCGTAAATCCGGAACCCTACCAAGGTGAAAGACCTTCAAGTTAATTCGTGGAACCTGCATGGCTCCTAACGCTTCCAGCAAAGCTACTTCTGTGAAAGCTGTGACGAGCAGAGGAAATGGGACAGGAGAGGGCGTGCACAGTTGTATCGCTAGGAGCCCCCAAAGTGATGACGGTCCTCGGGCCAGCATGGGAGTGCATTGGCACCATGTAAGGAAAGAGGGCCTCCCGTAGCACCGTTGGGTGGGAGCGGTGTGGGGTTGTTCGGAGAAGAAAAGTTTCCCATGAAGCTCTGTTTCAGCAAACGCGTGTCCACTTCCGTAGCAGCCTAAGCAGTCTTGCCTTCGTTAGACATTTTTCTTCATGCATATTTCTCTTACTGAAATGGTTCTAATATTTGTATAACAAGTATTTCGTGGCAAACGGAGAAAGTTGGAAGCAAAAATCTGTTCATAGAAATATGAGTAATATTAGTAACATTGCCTTCAGTGAAATTGAGAGCAGATCTAAAGGGATGTGAAAAGCATCAGGGTGCTCATATAGGAGGCAGGATCATTTCCCCCAGACCGCGGCCATGCGGGTTGTGTTTTATGGTAGGAGTGATTATGGCAGCCTATGTGTGTCTGGGCATAAGAATACTTATTCTATGGATCTTAAAAAGGTAATTATGTGTTGGAATTATGTGTTGGAAAATGTATGGCGTGGAATTCAGTAGGGGAGTGCTCACGATTTGTGTGGTTCTGGAGTTGGAAATGGGTGGCAGATCCAGCAAAGGGCAAGATTTCCAATGGACTGCTGAGTCATTCTTAGGGTGGGCTGGGAGAAAATGTGTTTTGGTCTGAAGGAGGGGAGGAAGAAGACAAAAACAAGTAAATTAGAAAACGTGGTTGCAGGATTGAAATCTGATCCTGAAAAAGAAGGAATAGCCATGAGTATAATGTTTAAAAATACACACAAAGAAATCCACTGTGGTGGGAGTCACAAGAGAAGTTCAATCATTATCTGGTCTCGTCATCTCGAGTGAGCTACATCCCTCCCAAGCCGACTGCTTGGTCCATGGCTCTTAGTTTTTGCATCTGGAGGCTTTTGTGGTTAGTGTTGGTTTGAGGTCATTTGGGCTGATCCATTGGTCTGGGTTTGTTCTTGTTTCTAC

This can be bypassed with the flag 'tossbrokenreads' or 'nullifybrokenquality'
        at shared.KillSwitch.kill(KillSwitch.java:96)
        at stream.Read.validateQualityLength(Read.java:217)
        at stream.Read.validate(Read.java:105)
        at stream.Read.<init>(Read.java:77)
        at stream.Read.<init>(Read.java:50)
        at stream.FASTQ.quadToRead_slow(FASTQ.java:851)
        at stream.FASTQ.toReadList(FASTQ.java:686)
        at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:107)
        at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:93)
        at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:682)
        at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:658)
```

**Comment by kristinelacek** [comment]
cc/ @nbx0

**Comment by kristinelacek** [comment]
https://github.com/CDCgov/spyne/commit/1c26788487c450b0be52128d5cc69d1c53729083
